name: QC_traits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        $CONDA/bin/flake8 traitator/
    - name: run python tests
      run: |
        $CONDA/bin/nosetests traitator --with-doctest
    # since we for now only check QC of traits no code has to be covered
    #    $CONDA/bin/nosetests traitator --with-doctest --with-coverage
    #- name: convert coverage
    #  run: |
    #    $CONDA/bin/coverage lcov
    #- name: send coverage report
    #  uses: coverallsapp/github-action@master
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    path-to-lcov: "coverage.lcov"
